### ISSUE TITLE
URI::BadURIError: both URI are relative

### ISSUE THREAD

**Issue by joel** [moonmaster9000/dupe#20]
I try your sample 

```
irb# require 'dupe'

irb# Dupe.create :author, :name => 'Monkey', :published => true

irb# Dupe.create :author, :name => 'Tiger', :published => false

irb# class Author < ActiveResource::Base; self.site = '';self.format = :xml; end

irb# Get %r{/authors/published.xml} do
irb#    Dupe.find(:authors) {|a| a.published == true}
irb# end    

irb# Author.find :all, :from => :published
```

I have this message 

```
URI::BadURIError: both URI are relative
```

Env :

```
irb --version
irb 0.9.6(09/06/30)

rails -v
Rails 3.1.0.rc1

ruby -v
ruby 1.9.2p180 (2011-02-18 revision 30909) [x86_64-darwin10.7.0]
```

**Comment by moonmaster9000** [comment]
Hi sorry need to update the readme for rails 3. even when testing, you can no longer supply an empty self.host setting. try something like self.host='http://localhost'

**Comment by moonmaster9000** [comment]
sorry, meant `self.site='http://localhost'`

**Comment by joel** [comment]
When i try with XML Format :

```
irb# require 'dupe'

irb# Dupe.create :author, :name => 'Monkey', :published => true

irb# Dupe.create :author, :name => 'Tiger', :published => false

irb# class Author < ActiveResource::Base; self.site='http://localhost'; self.format = :xml; end

irb# Get %r{/authors/published.xml} do
irb#     Dupe.find(:authors) {|a| a.published == true}
irb# end

irb# Author.find :all, :from => :published
```

I obtain this message :

```
irb# NoMethodError: undefined method `body' for [{"id"=>1, "name"=>"Monkey", "published"=>true}]:Array
```

And with Json format 

```
irb# require 'dupe'

irb# Dupe.create :author, :name => 'Monkey', :published => true

irb# Dupe.create :author, :name => 'Tiger', :published => false

irb# class Author < ActiveResource::Base; self.site='http://localhost'; self.format = :json; end

irb# Get %r{/authors/published.json} do
irb#    Dupe.find(:authors) {|a| a.published == true}
irb# end

irb# Author.find :all, :from => :published
```

I obtain this message :

```
MultiJson::DecodeError: 706: unexpected token at '<?xml version="1.0" encoding="UTF-8"?>
<authors type="array">
  <author>
    <id type="integer">1</id>
    <name>Monkey</name>
    <published type="boolean">true</published>
  </author>
</authors>
'
    from /Users/joel/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/json/common.rb:146:in `parse'
    from /Users/joel/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/json/common.rb:146:in `parse'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/multi_json-1.0.3/lib/multi_json/engines/json_gem.rb:13:in `decode'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/multi_json-1.0.3/lib/multi_json.rb:65:in `decode'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/activesupport-3.1.0.rc4/lib/active_support/json/decoding.rb:12:in `decode'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/activeresource-3.1.0.rc4/lib/active_resource/formats/json_format.rb:21:in `decode'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/dupe-0.6.0/lib/dupe/active_resource_extensions.rb:22:in `get'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/activeresource-3.1.0.rc4/lib/active_resource/custom_methods.rb:57:in `get'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/activeresource-3.1.0.rc4/lib/active_resource/base.rb:887:in `find_every'
    from /Users/joel/.rvm/gems/ruby-1.9.2-p180@miel_client/gems/activeresource-3.1.0.rc4/lib/active_resource/base.rb:806:in `find'
    from (irb):8
    from /Users/joel/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in `<main>'
```

I have updated rails to rc4

```
rails -v
Rails 3.1.0.rc4
```

**Comment by moonmaster9000** [comment]
ah, thx Joel, didn't notice that you were using rails 3.1. I haven't tried to get Dupe working on Rails 3.1 yet; I should have some time this week to upgrade it, though if you feel like trying it yourself and sending a pull request, that would be much appreciated too!

**Comment by moonmaster9000** [comment]
dupe supports rails 3.1 now; version 1.0.0+
